### ISSUE TITLE
Standoff Size

### ISSUE THREAD

**Issue by ghost** [FSund/pteron-keyboard#1]
What size standoffs are you using for the plates?

**Comment by FSund** [comment]
That's a good question. I'll dig up the board later today and take some measurements. Perhaps I should include a bill of materials in the readme.

**Comment by FSund** [comment]
The one in the photo in the readme is built using 9mm brass spacers, but can theoretically be built with spacers as low as 5 mm. I would probably go for at least 8 mm if you're not very familiar with handwiring.
