### ISSUE TITLE
Adjusting the design

### ISSUE THREAD

**Issue by jceb** [FSund/pteron-keyboard#2]
Hi, thank you for creating the keyboard! I started playing around with the SVG files and found that really hard. Did you us a script for creating the keyboard SVG? If so, would you be willing to share it?

**Comment by FSund** [comment]
Sorry, this was all hand-crafted in Inkscape, so I've just worked directly on the SVG files. I do agree it's a bit hard to edit though, and would prefer to have it set up in a proper parametric way. Feel free to re-implement it in your 2d modelling software of choice 😅

**Comment by jceb** [comment]
Okay, thank you for the information. Great job designing it solely in Inkscape :+1:
