### ISSUE TITLE
Design alterations

### ISSUE THREAD

**Issue by Kraken-Jokes** [FSund/pteron-keyboard#3]
Howdy! 
Awesome design, I've built two so far and love them fiercely. In building those I decided that my 'share and share alike' was going to be recreating the files in .dxf format. 
I have the files for the Pteron56 ready to go, I just wanted to start an issue to see if sending that pull request would be cool. 
I also have an image of my build I'd like to add

**Comment by FSund** [comment]
Cool! I never got further than the one prototype, so I get very excited when I see other people liking the design.

Instructions for converting to dxf is included in the readme, but including files ready to go might me a good idea. A PR is always welcome. I might not have time to look at in a couple of days though.

Pictures of builds are of course very welcome!

**Comment by Kraken-Jokes** [comment]
Sounds good!
I've also made a version of the 56 that has encoder, backlight, and teensy2.0 support. Since it's different enough I'm calling it pteron_v2 on my local machine, but wanted to get your input on that name before I put it on github (I don't want to take the name if you're planning on using it).

**Comment by FSund** [comment]
Sorry for the late reply here, just noticed your comment. Go ahead with pteron_v2, that sounds like a cool project.
